services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    user: "root"
    command:
      - --unix-socket=/cloudsql
      - my-salon-cast:us-west1:mysaloncast-db
    volumes:
      - ./gcp-credentials.json:/config/gcp-credentials.json:ro
      - cloudsql:/cloudsql
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-credentials.json

  app:
    build: .
    depends_on:
      - cloud-sql-proxy
    volumes:
      - ./gcp-credentials.json:/app/gcp-credentials.json:ro
      - cloudsql:/cloudsql
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

volumes:
  cloudsql:
