"""
Prompt templates for MySalonCast LLM service.
"""

from .templates import (
    SOURCE_ANALYSIS_TEMPLATE,
    PERSONA_RESEARCH_TEMPLATE,
    PODCAST_OUTLINE_TEMPLATE,
    SEGMENT_DIALOGUE_TEMPLATE,
)

__all__ = [
    "SOURCE_ANALYSIS_TEMPLATE",
    "PERSONA_RESEARCH_TEMPLATE", 
    "PODCAST_OUTLINE_TEMPLATE",
    "SEGMENT_DIALOGUE_TEMPLATE",
]
